default_config:
logger:
  default: error
  logs:
    custom_components.blueprint: debug



blueprint:
  username: my_username
  password: my_password
  binary_sensor:
    - enabled: true
      name: My custom name
  sensor:
    - enabled: true
      name: My custom name
  switch:
    - enabled: true
      name: My custom name